/**
 * Local Anvil token addresses (Cartesi CLI 1.5).
 * Generated by scripts/deploy-minter-wwart.mjs --promote
 */
export const LOCAL_WWART = {
  address: '0xBc174Ba3265e5E0FbdEFa2A8c9FDa5F334471287',
  symbol: 'wWART',
  name: 'Wrapped WART',
  decimals: 18,
  chainId: 31337,
  openMint: false,
  minterOnly: true,
  minter: '0xab7528bb862fB57E8A2BCd567a2e929a0Be56a5e',
  note: 'Minter-only. L1 mint via authorized minter / voucher — no free faucet.',
};

/** @deprecated alias */
export const WWART_ADDRESS = LOCAL_WWART.address;
