/**
 * Local Anvil token addresses (Cartesi CLI 1.5).
 * Generated by scripts/deploy-minter-wwart.mjs --promote
 */
export const LOCAL_WWART = {
  address: '0x663F3ad617193148711d28f5334eE4Ed07016602',
  symbol: 'wWART',
  name: 'Wrapped WART',
  decimals: 18,
  chainId: 31337,
  openMint: false,
  minterOnly: true,
  minter: '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC',
  note: 'Minter-only. L1 mint via authorized minter / voucher — no free faucet.',
};

/** @deprecated alias */
export const WWART_ADDRESS = LOCAL_WWART.address;
